apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: job-portal
spec:
  type: NodePort  # or LoadBalancer if on cloud
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # you can access it on localhost:30080
