apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8001         # <- external port (accessible within cluster)
      targetPort: 8001   # <- port exposed by container
  type: ClusterIP
