name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]  # runs when you push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_PREFIX: yourdockerhubusername  # replace this

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push auth-service
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/auth-service:latest

      - name: Build and Push job-service
        uses: docker/build-push-action@v5
        with:
          context: ./job-service
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/job-service:latest

      - name: Build and Push notification-service
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/notification-service:latest
